idbarang = "14" --change id block that you use for amogus

function placeTile(id, x, y)
    pkt = {}
    pkt.type = 3
    pkt.int_data = id
    pkt.int_x = x
    pkt.int_y = y
    pkt.pos_x = getLocal().pos.x
    pkt.pos_y = getLocal().pos.y
    sendPacketRaw(false, pkt)
end



findPath((getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32 - 4)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 1)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 1)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 1)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)

findPath((getLocal().pos.x) / 32 + 1, getLocal().pos.y / 32 + 3)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 3)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)

findPath((getLocal().pos.x) / 32 + 1, getLocal().pos.y / 32 + 6)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 1)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 1)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 1)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 1)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 1)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 1)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 1)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)

findPath((getLocal().pos.x) / 32 + 1, getLocal().pos.y / 32 + 7)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 7)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 1)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)

findPath((getLocal().pos.x) / 32 + 1, getLocal().pos.y / 32 + 8)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 1)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 2)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 1)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 1)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 3)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32 + 1, getLocal().pos.y / 32 + 7)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 2)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 2)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 3)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)

findPath((getLocal().pos.x) / 32 + 1, getLocal().pos.y / 32 + 8)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 1)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 2)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 2)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 3)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)

findPath((getLocal().pos.x) / 32 + 1, getLocal().pos.y / 32 + 8)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 3)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 2)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 2)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 1)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)

findPath((getLocal().pos.x) / 32 + 1, getLocal().pos.y / 32 + 8)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 1)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 1)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 1)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 1)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 1)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 1)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
findPath((getLocal().pos.x) / 32, getLocal().pos.y / 32 - 1)
sleep(200)
placeTile(idbarang,(getLocal().pos.x) / 32 - 1, getLocal().pos.y / 32)
sleep(80)
